 var gData = {
  "nodes": [
{"id": "Yang, Hsin-Chou", "group":0, "short":""},
{"id": "Chen, Chun-houh", "group":0, "short":""},
{"id": "Wang, Jen-Hung", "group":0, "short":""},
{"id": "Liao, Hsiao-Chi", "group":0, "short":""},
{"id": "Yang, Chih-Ting", "group":0, "short":""},
{"id": "Chen, Chia-Wei", "group":0, "short":""},
{"id": "Lin, Yin-Chun", "group":0, "short":""},
{"id": "Lu, Mei-Yeh Jade", "group":0, "short":""},
{"id": "Liao, James C", "group":0, "short":""},
{"id": "Hsieh, Chih-Hung", "group":0, "short":""},
{"id": "Chu, Yu-Feng", "group":0, "short":""},
{"id": "Kuang, Yu-Ting", "group":0, "short":""},
{"id": "Yang, Chuan-Kai", "group":0, "short":""},
{"id": "Nakano, Junji", "group":0, "short":""},
{"id": "Shieh, Sheau-Hue", "group":0, "short":""},
{"id": "Tien, Yin-Jing", "group":0, "short":""},
{"id": "Wu, Han-Ming", "group":0, "short":""},
{"id": "Chiu, Ming-Jang", "group":0, "short":""},
{"id": "Hua, Mau-Sun", "group":0, "short":""},
{"id": "Chen, Ta-Fu", "group":0, "short":""},
{"id": "Hwu, Hai-Gwo", "group":0, "short":""},
{"id": "Lai, Yuan-Cheng", "group":0, "short":""},
{"id": "Lo, Nai-Wei", "group":0, "short":""},
{"id": "Lee, Tsung-Ju", "group":0, "short":""},
{"id": "Tseng, Shian-Shyong", "group":0, "short":""},
{"id": "Chen, Hsing-Chung", "group":0, "short":""},
{"id": "Lin, Sung-Chiang", "group":0, "short":""},
{"id": "Dai, Jyun-Han", "group":0, "short":""},
{"id": "Ko, Ru", "group":0, "short":""},
{"id": "Lai, Chi-Ping", "group":0, "short":""},
{"id": "Mao, Ching-Hao", "group":0, "short":""},
{"id": "Hsu, Chien-Lung", "group":0, "short":""},
{"id": "Lee, Kuo-Chen", "group":0, "short":""},
{"id": "Lai, Chia-Min", "group":0, "short":""},
{"id": "Jang, Wen-Jung", "group":0, "short":""},
{"id": "Tzeng, ShengLi", "group":0, "short":""},
{"id": "Yang, Cheng-Zen", "group":0, "short":""},
{"id": "Kwon, Oh-Hyun", "group":0, "short":""},
{"id": "Ma, Kwan-Liu", "group":0, "short":""},
{"id": "Chang, Li-Chun", "group":0, "short":""},
{"id": "Hsu, Yi-Chiung", "group":0, "short":""},
{"id": "Chiu, Han-Mo", "group":0, "short":""},
{"id": "Ueda, Koji", "group":0, "short":""},
{"id": "Wu, Ming-Shiang", "group":0, "short":""},
{"id": "Shen, Tang-Long", "group":0, "short":""},
{"id": "Lin, Jie", "group":0, "short":""},
{"id": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "group":1, "short":""},
{"id": "Using data visualization technique to detect sensitive information re-identification problem of real open dataset", "group":1, "short":""},
{"id": "Exploratory data analysis of interval-valued symbolic data with matrix visualization", "group":1, "short":""},
{"id": "Brain responses of explicit and implicit memory: An event-related potential study", "group":1, "short":""},
{"id": "Privacy-preserving encryption-domain video retrieval over the cloud via block transformations of key frames", "group":1, "short":""},
{"id": "A Frame-Based Approach to Generating Insider Threat Test Suite on Cloud File-Sharing", "group":1, "short":""},
{"id": "MITC Viz: Visual Analytics for Man-in-the-Cloud Threats Awareness", "group":1, "short":""},
{"id": "Odd visualizer: Scalable open data de-identification visualizer", "group":1, "short":""},
{"id": "Sec-Buzzers: a Web Service for Exploring Cyber Security Emerging Topics based on Social Network Mining", "group":1, "short":""},
{"id": "Matrix visualization and information mining", "group":1, "short":""},
{"id": "Visualizing large hierarchical information structures in digital libraries", "group":1, "short":""},
{"id": "Dimension Reduction and Visualization of Symbolic Interval-Valued Data Using Sliced Inverse Regression", "group":1, "short":""},
{"id": "A Deep Generative Model for Reordering Adjacency Matrices", "group":1, "short":""},
{"id": "Exploration of the Proteomic Landscape of Small Extracellular Vesicles in Serum as Biomarkers for Early Detection of Colorectal Neoplasia", "group":1, "short":""},
{"id": "Visualizing NBA information via storylines", "group":1, "short":""}
  ],
  "links": [
{"source": "Yang, Hsin-Chou", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Chen, Chun-houh", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Wang, Jen-Hung", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Liao, Hsiao-Chi", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Yang, Chih-Ting", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Chen, Chia-Wei", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Lin, Yin-Chun", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Lu, Mei-Yeh Jade", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Liao, James C", "target": "Analysis of genomic distributions of SARS-CoV-2 reveals a dominant strain type with strong allelic associations", "value":0},
{"source": "Hsieh, Chih-Hung", "target": "Using data visualization technique to detect sensitive information re-identification problem of real open dataset", "value":0},
{"source": "Chu, Yu-Feng", "target": "Using data visualization technique to detect sensitive information re-identification problem of real open dataset", "value":0},
{"source": "Kuang, Yu-Ting", "target": "Using data visualization technique to detect sensitive information re-identification problem of real open dataset", "value":0},
{"source": "Yang, Chuan-Kai", "target": "Using data visualization technique to detect sensitive information re-identification problem of real open dataset", "value":0},
{"source": "Nakano, Junji", "target": "Exploratory data analysis of interval-valued symbolic data with matrix visualization", "value":0},
{"source": "Shieh, Sheau-Hue", "target": "Exploratory data analysis of interval-valued symbolic data with matrix visualization", "value":0},
{"source": "Tien, Yin-Jing", "target": "Exploratory data analysis of interval-valued symbolic data with matrix visualization", "value":0},
{"source": "Wu, Han-Ming", "target": "Exploratory data analysis of interval-valued symbolic data with matrix visualization", "value":0},
{"source": "Yang, Chuan-Kai", "target": "Exploratory data analysis of interval-valued symbolic data with matrix visualization", "value":0},
{"source": "Chen, Chun-houh", "target": "Exploratory data analysis of interval-valued symbolic data with matrix visualization", "value":0},
{"source": "Chiu, Ming-Jang", "target": "Brain responses of explicit and implicit memory: An event-related potential study", "value":0},
{"source": "Hua, Mau-Sun", "target": "Brain responses of explicit and implicit memory: An event-related potential study", "value":0},
{"source": "Chen, Ta-Fu", "target": "Brain responses of explicit and implicit memory: An event-related potential study", "value":0},
{"source": "Hwu, Hai-Gwo", "target": "Brain responses of explicit and implicit memory: An event-related potential study", "value":0},
{"source": "Chen, Chun-houh", "target": "Brain responses of explicit and implicit memory: An event-related potential study", "value":0},
{"source": "Yang, Chuan-Kai", "target": "Privacy-preserving encryption-domain video retrieval over the cloud via block transformations of key frames", "value":0},
{"source": "Lai, Yuan-Cheng", "target": "Privacy-preserving encryption-domain video retrieval over the cloud via block transformations of key frames", "value":0},
{"source": "Lo, Nai-Wei", "target": "Privacy-preserving encryption-domain video retrieval over the cloud via block transformations of key frames", "value":0},
{"source": "Lee, Tsung-Ju", "target": "A Frame-Based Approach to Generating Insider Threat Test Suite on Cloud File-Sharing", "value":0},
{"source": "Tseng, Shian-Shyong", "target": "A Frame-Based Approach to Generating Insider Threat Test Suite on Cloud File-Sharing", "value":0},
{"source": "Chen, Hsing-Chung", "target": "A Frame-Based Approach to Generating Insider Threat Test Suite on Cloud File-Sharing", "value":0},
{"source": "Lin, Sung-Chiang", "target": "A Frame-Based Approach to Generating Insider Threat Test Suite on Cloud File-Sharing", "value":0},
{"source": "Dai, Jyun-Han", "target": "MITC Viz: Visual Analytics for Man-in-the-Cloud Threats Awareness", "value":0},
{"source": "Ko, Ru", "target": "MITC Viz: Visual Analytics for Man-in-the-Cloud Threats Awareness", "value":0},
{"source": "Kuang, Yu-Ting", "target": "MITC Viz: Visual Analytics for Man-in-the-Cloud Threats Awareness", "value":0},
{"source": "Lai, Chi-Ping", "target": "MITC Viz: Visual Analytics for Man-in-the-Cloud Threats Awareness", "value":0},
{"source": "Mao, Ching-Hao", "target": "MITC Viz: Visual Analytics for Man-in-the-Cloud Threats Awareness", "value":0},
{"source": "Hsieh, Chih-Hung", "target": "Odd visualizer: Scalable open data de-identification visualizer", "value":0},
{"source": "Hsu, Chien-Lung", "target": "Odd visualizer: Scalable open data de-identification visualizer", "value":0},
{"source": "Chu, Yu-Feng", "target": "Odd visualizer: Scalable open data de-identification visualizer", "value":0},
{"source": "Kuang, Yu-Ting", "target": "Odd visualizer: Scalable open data de-identification visualizer", "value":0},
{"source": "Hsieh, Chih-Hung", "target": "Sec-Buzzers: a Web Service for Exploring Cyber Security Emerging Topics based on Social Network Mining", "value":0},
{"source": "Lee, Kuo-Chen", "target": "Sec-Buzzers: a Web Service for Exploring Cyber Security Emerging Topics based on Social Network Mining", "value":0},
{"source": "Mao, Ching-Hao", "target": "Sec-Buzzers: a Web Service for Exploring Cyber Security Emerging Topics based on Social Network Mining", "value":0},
{"source": "Lai, Chia-Min", "target": "Sec-Buzzers: a Web Service for Exploring Cyber Security Emerging Topics based on Social Network Mining", "value":0},
{"source": "Dai, Jyun-Han", "target": "Sec-Buzzers: a Web Service for Exploring Cyber Security Emerging Topics based on Social Network Mining", "value":0},
{"source": "Chen, Chun-houh", "target": "Matrix visualization and information mining", "value":0},
{"source": "Hwu, Hai-Gwo", "target": "Matrix visualization and information mining", "value":0},
{"source": "Jang, Wen-Jung", "target": "Matrix visualization and information mining", "value":0},
{"source": "Tien, Yin-Jing", "target": "Matrix visualization and information mining", "value":0},
{"source": "Tzeng, ShengLi", "target": "Matrix visualization and information mining", "value":0},
{"source": "Wu, Han-Ming", "target": "Matrix visualization and information mining", "value":0},
{"source": "Yang, Cheng-Zen", "target": "Visualizing large hierarchical information structures in digital libraries", "value":0},
{"source": "Wu, Han-Ming", "target": "Dimension Reduction and Visualization of Symbolic Interval-Valued Data Using Sliced Inverse Regression", "value":0},
{"source": "Chen, Chun-houh", "target": "Dimension Reduction and Visualization of Symbolic Interval-Valued Data Using Sliced Inverse Regression", "value":0},
{"source": "Chen, Chun-houh", "target": "A Deep Generative Model for Reordering Adjacency Matrices", "value":0},
{"source": "Kwon, Oh-Hyun", "target": "A Deep Generative Model for Reordering Adjacency Matrices", "value":0},
{"source": "Ma, Kwan-Liu", "target": "A Deep Generative Model for Reordering Adjacency Matrices", "value":0},
{"source": "Chang, Li-Chun", "target": "Exploration of the Proteomic Landscape of Small Extracellular Vesicles in Serum as Biomarkers for Early Detection of Colorectal Neoplasia", "value":0},
{"source": "Hsu, Yi-Chiung", "target": "Exploration of the Proteomic Landscape of Small Extracellular Vesicles in Serum as Biomarkers for Early Detection of Colorectal Neoplasia", "value":0},
{"source": "Chiu, Han-Mo", "target": "Exploration of the Proteomic Landscape of Small Extracellular Vesicles in Serum as Biomarkers for Early Detection of Colorectal Neoplasia", "value":0},
{"source": "Ueda, Koji", "target": "Exploration of the Proteomic Landscape of Small Extracellular Vesicles in Serum as Biomarkers for Early Detection of Colorectal Neoplasia", "value":0},
{"source": "Wu, Ming-Shiang", "target": "Exploration of the Proteomic Landscape of Small Extracellular Vesicles in Serum as Biomarkers for Early Detection of Colorectal Neoplasia", "value":0},
{"source": "Shen, Tang-Long", "target": "Exploration of the Proteomic Landscape of Small Extracellular Vesicles in Serum as Biomarkers for Early Detection of Colorectal Neoplasia", "value":0},
{"source": "Lin, Jie", "target": "Visualizing NBA information via storylines", "value":0},
{"source": "Yang, Chuan-Kai", "target": "Visualizing NBA information via storylines", "value":0}
  ]
}